# -*- coding: utf-8 -*-
"""vaccum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aCQ5VESUK3Lzkg6omAqZCPSylR_0eVbu
"""

# Vacuum Cleaner Agent – 6 Rooms, 3 Parts Each

rooms = ["Kitchen", "Hall", "Bedroom1", "Bedroom2", "Balcony", "StoreRoom"]
parts = ["Left", "Center", "Right"]

# 1 = Dirty, 0 = Clean
environment = {room: [1, 1, 1] for room in rooms}

step = 1
cleaned_parts = 0
total_parts = len(rooms) * len(parts)
percept_sequence = []

print("\nOUTPUT\n")
print(f"{'STEP':<5}{'ROOM':<12}{'PART':<8}{'PERCEPT':<10}{'ACTION':<8}{'PERFORMANCE'}")
print("-" * 60)

for room in rooms:
    for i in range(3):
        part = parts[i]

        if environment[room][i] == 1:
            percept = "Dirty"
            action = "SUCK"
            environment[room][i] = 0
            cleaned_parts += 1
        else:
            percept = "Clean"
            action = "NO-OP"

        performance = int((cleaned_parts / total_parts) * 100)

        percept_sequence.append((room, part, percept))

        print(f"{step:<5}{room:<12}{part:<8}{percept:<10}{action:<8}{performance}%")
        step += 1

# ---------------- FINAL STATUS ----------------
print("\nFINAL STATUS OF ROOMS\n")
for room in environment:
    print(f"{room:<10}: {environment[room]}")

# ---------------- PERCEPT SEQUENCE ----------------
print("\nPERCEPT SEQUENCE\n")
for i, p in enumerate(percept_sequence, start=1):
    print(f"{i}. ({p[0]}, {p[1]}, {p[2]})")

print("\nThank you for using the cleaner 😊")